import { JOBS, buildQuestions } from './question-bank.js';

const KEY='future-career-application-v1';
const initial={screen:'splash',coins:0,coinsAwarded:false,purchased:[],gift:null,giftOpened:false,category:'all',companyType:null,jobId:null,organization:'',questionIndex:0,questions:null,answers:{}};
const saved=JSON.parse(localStorage.getItem(KEY)||'{}');
let state={...initial,...saved};
if(!state.coinsAwarded) state.screen='splash';
let timer=null;
const app=document.querySelector('#app');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const go=(screen,extra={})=>{state={...state,screen,...extra};save();render();};
const esc=(v='')=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const categories=[['all','전체'],['academic','학업·연구'],['practical','실무'],['challenge','도전'],['global','글로벌'],['leadership','리더십'],['skill','역량']];
const experiences=[
	['undergrad','학부연구생','academic','질문을 세우고 검증하는 탐구 경험',15],['master','대학원 석사','academic','전문 분야를 깊게 탐구하는 학업 경험',20,'undergrad'],['minor','복수전공 / 부전공','academic','관심 분야를 넓혀 연결하는 학업 경험',12],['research-project','연구 프로젝트','academic','팀과 함께 연구 질문을 해결한 경험',16],['conference','논문·학회 발표','academic','연구 결과를 정리하고 공유한 경험',18,'research-project'],
	['intern','기업 인턴','practical','조직의 실제 문제를 가까이서 관찰한 경험',18],['field-training','현장실습','practical','현장에서 직무를 직접 경험한 시간',14],['company-project','기업 프로젝트','practical','기업의 실제 과제를 해결한 경험',21],
	['contest-entry','공모전 참여','challenge','아이디어를 결과물로 만든 첫 도전',8],['contest-encourage','공모전 장려상','challenge','끝까지 완성해 인정받은 도전',12,'contest-entry'],['contest-award','공모전 우수상','challenge','높은 완성도로 만든 성과',18,'contest-encourage'],['contest-best','공모전 최우수상','challenge','가장 높은 목표를 향한 도전',24,'contest-award'],['hackathon','해커톤','challenge','짧은 시간 안에 팀으로 만든 결과',15],['startup','창업 경험','challenge','문제를 발견하고 실행한 경험',22],
	['exchange-us','교환학생 · 미국·캐나다','global','새로운 환경에서 배우고 적응한 경험',8],['exchange-eu','교환학생 · 유럽','global','다른 문화와 관점 속에서 성장한 경험',7],['exchange-asia','교환학생 · 아시아','global','가까운 이웃 국가에서 확장한 경험',6],['overseas-training','해외연수','global','낯선 환경에서 역량을 키운 경험',9],['language','어학 경험','global','다른 언어로 소통하는 힘',7],
	['club-staff','동아리 운영진','leadership','사람과 활동을 꾸준히 운영한 경험',10],['student-member','학생회 부원','leadership','공동체의 일원으로 기여한 경험',7],['student-deputy','학생회 차장','leadership','업무를 조율하고 책임진 경험',10,'student-member'],['council','학생회 국장','leadership','사람과 목표를 연결한 협업 경험',14,'student-deputy'],['student-president','학생회 회장','leadership','조직 전체의 방향을 책임진 경험',20,'council'],
	['data','데이터분석 프로젝트','skill','데이터로 문제를 정의하고 해석한 경험',16],['coding','코딩 프로젝트','skill','기술로 아이디어를 구현한 경험',17],['portfolio','포트폴리오','skill','나의 역량을 결과물로 정리한 경험',12],['certificate','직무 자격증','skill','기초 전문성을 증명하는 준비',10],['shift','SHIFT 프로그램 기획 경험','skill','사용자 관점에서 프로그램을 설계한 경험',16]
];
const gifts=['SHIFT 프로그램 기획 경험','SHIFT 운영진 경험','SHIFT IT 온보딩 진행 경험','SHIFT 헬스케어 기업 탐방 경험','SHIFT 소모임 진행 경험'];
const header=(body)=>`<div class="app-shell"><header class="topbar"><button class="home-button" data-action="home">⌂ HOME</button><div class="logo">FUTURE <span>CAREER</span></div><div class="header-tools"><div class="mono">APPLICATION STUDIO / 2026</div><button class="reset-demo" data-action="reset-demo">RESET DEMO</button></div></header>${body}</div>`;
function render(){if(state.screen==='splash')return splash();if(state.screen==='gacha')return gacha();if(state.screen==='shop')return shop();if(state.screen==='mystery')return mystery();if(state.screen==='recruit')return recruit();if(state.screen==='type')return typePage();if(state.screen==='job')return jobPage();if(state.screen==='org')return orgPage();if(state.screen==='essay')return essay();if(state.screen==='complete')return complete();if(state.screen==='resume')return resume();}
function splash(){app.innerHTML='<div class="splash-screen"><div class="splash-mark"><div class="splash-kicker">MY FUTURE, MY SHIFT</div><div class="splash-logo">FUTURE <span>RESUME</span></div><p>나의 경험을 미래의 지원서로</p></div></div>';if(!timer)timer=setTimeout(()=>{timer=null;go('gacha');},1500);}
function gacha(){const reward=Math.floor(Math.random()*31)+40;app.innerHTML='<div class="gacha-screen"><div class="gacha-copy"><div class="splash-kicker">SHIFT LUCKY DROP</div><h1>오늘의<br> 미래 코인을<br><span>뽑아보세요.</span></h1><p>가챠 머신이 첫 Career Shop 코인을 준비하고 있습니다.</p></div><div class="gacha-machine"><div class="machine-top"><span></span><span></span><span></span><span></span><span></span></div><div class="machine-glass"><i class="capsule capsule-one"></i><i class="capsule capsule-two"></i><i class="capsule capsule-three"></i><i class="capsule capsule-four"></i><i class="capsule capsule-five"></i><i class="winning-capsule">◈</i></div><div class="machine-base"><div class="machine-label">FUTURE<br>RESUME</div><div class="machine-slot"></div><div class="machine-knob"></div></div></div><div class="gacha-status"><span class="status-shuffle">CAPSULES SHUFFLING · · ·</span><span class="status-reveal">YOUR CAPSULE IS READY</span><strong class="gacha-reward">◈ ' + reward + '</strong><div class="gacha-result" style="display:none"><div class="result-label">YOU GOT</div><strong>◈ ' + reward + ' COINS</strong><p>Career Shop 코인을 획득했습니다.</p><div class="gacha-result-actions"><button class="button secondary" data-action="cancel-reward">취소</button><button class="button accent" data-action="claim-coins">코인 받기 </button></div></div></div></div>';if(!timer)timer=setTimeout(()=>{timer=null;document.querySelector('.gacha-screen')?.classList.add('complete');const result=document.querySelector('.gacha-result');if(result)result.style.display='grid';},4300);}
function shop(){const visible=experiences.filter(item=>state.category==='all'||item[2]===state.category);const tabs=categories.map(([id,label])=>`<button class="category-tab ${state.category===id?'active':''}" data-category="${id}">${label}</button>`).join('');const cards=visible.map(([id,label,category,detail,cost,requires])=>{const ownedCount=state.purchased.filter(item=>item===id).length;const prerequisite=requires?experiences.find(item=>item[0]===requires)?.[1]:'';const locked=requires&&!state.purchased.includes(requires);const controls=ownedCount?`<div class="quantity-control"><button class="quantity-button" data-decrease="${id}" aria-label="${label} 수량 줄이기">−</button><span class="owned-label">${ownedCount}개 보유</span><button class="quantity-button" data-increase="${id}" aria-label="${label} 수량 늘리기">+</button></div>`:`<button class="button small" data-buy="${id}" ${state.coins<cost||locked?'disabled':''}>${locked?'잠김':'구매하기'}</button>`;return `<article class="shop-item ${ownedCount?'owned':''} ${locked?'locked':''}"><div><div class="mono">${categories.find(item=>item[0]===category)?.[1]||'CAREER EXPERIENCE'}</div><h3>${label}</h3><p>${detail}</p>${locked?`<div class="prerequisite">${prerequisite} 경험 필요</div>`:''}</div><div class="shop-item-footer"><span class="coin-cost">${cost} COINS</span><div class="shop-item-actions">${controls}</div></div></article>`;}).join('');app.innerHTML=header(`<main class="shop-page"><div class="eyebrow">CAREER SHOP / EXPERIENCE STORE</div><div class="shop-title-row"><div><h1> EXPERIENCE STORE</h1><p class="lead">미래의 나를 상상하며, 필요한 경험을 하나씩 구매해보세요.</p></div><div class="coin-wallet"><span>MY COINS</span><strong>${state.coins} COINS</strong><small>획득 내역 보기 →</small></div></div><div class="category-tabs">${tabs}</div><div class="shop-grid">${cards}</div><div class="actions"><button class="button accent" data-action="finish-shop">지원하러 가기 →</button></div></main>`);}
function mystery(){const labels=state.purchased.map(id=>experiences.find(x=>x[0]===id)?.[1]).filter(Boolean);const giftStage=state.giftOpened?`<section class="mystery-reveal"><div class="reward-decor reward-decor-left"></div><div class="reward-decor reward-decor-right"></div><div class="eyebrow">CONGRATULATIONS!</div><h2>축하합니다!</h2><div class="reward-highlight">${state.gift} 당첨!</div><p>SHIFT가 당신의 대학생활을 응원합니다.<br>새로운 경험이 MY CAREER에 추가되었습니다.</p><button class="button accent" data-action="confirm-gift">확인하기 →</button></section>`:`<section class="mystery-gift-stage"><div class="side-note note-left">SHIFT가 준비한<br>특별한 경험!</div><div class="mystery-decor decor-one"></div><div class="mystery-decor decor-two"></div><div class="gift-illustration"><img src="mystery-box.png" alt="SHIFT Mystery Box 선물상자"></div><div class="side-note note-right">A SMALL GIFT<br>BY SHIFT</div><button class="button accent mystery-cta" data-action="open-gift">선물 열어보기</button></section>`;app.innerHTML=header(`<main class="mystery-page"><div class="eyebrow"> SHIFT MYSTERY BOX</div><h1><span>SHIFT</span> MYSTERY GIFT</h1><p class="lead">구매한 경험과는 별개로, SHIFT의 랜덤 보너스를 확인해보세요.</p>${giftStage}<section class="mystery-info-card"><div><span>MY EXPERIENCE</span><strong>${labels.length}개 보유</strong></div><div><span>SHIFT BONUS</span><strong>1개</strong></div><div class="mystery-tip"><span>TIP</span><p>SHIFT Mystery Box에서는 구매한 경험과는 다른 특별한 경험이 지급됩니다.</p></div></section></main>`);}
function recruit(){app.innerHTML=header(`<main class="recruit-page"><div class="recruit-hero"><div class="eyebrow">RECRUIT / FUTURE CAREER</div><h1>미래를 함께 만들어갈<br><span>인재를 기다립니다.</span></h1><p>이제 경험을 지원 직무와 연결하고, 나만의 미래 지원서를 시작해보세요.</p><div class="recruit-gift"><span class="badge">SPECIAL GIFT</span><strong>${state.gift||'SHIFT 보너스 경험'}</strong><span>SHIFT가 당신의 대학생활을 응원합니다.</span></div><button class="button accent" data-action="mystery">SHIFT Mystery Box 확인하기 →</button></div><div class="recruit-strip"><span>YOUR EXPERIENCE</span><strong>경험을 선택했다면, 이제 지원할 미래를 고릅니다.</strong></div></main>`);}
function typePage(){app.innerHTML=header(`<main><div class="eyebrow"> WHERE DO YOU WANT TO WORK?</div><h1>어떤 조직의 미래에 지원하시겠습니까?</h1><div class="cards"><article class="card"><div class="icon">🏢</div><h3>PRIVATE COMPANY</h3><p>성과와 성장, 직무 전문성, 기업 핵심가치를 중심으로 작성합니다.</p><button class="button" data-type="private">사기업 지원하기 →</button></article><article class="card"><div class="icon">🏛</div><h3>PUBLIC INSTITUTION</h3><p>직무수행능력, 문제해결, 직업윤리와 공공성을 중심으로 작성합니다.</p><button class="button" data-type="public">공기업·공공기관 지원하기 →</button></article></div></main>`);}
function jobPage(){const list=state.companyType==='public'?JOBS:[...JOBS].sort((a,b)=>Number(a.public)-Number(b.public));app.innerHTML=header(`<main><div class="eyebrow"> JOB CATEGORY</div><h1>지원 직무를 선택하세요</h1><div class="job-grid">${list.map(x=>`<button class="job ${x.id===state.jobId?'selected':''}" data-job="${x.id}"><strong>${x.label}</strong>${x.public?'<small>Public-ready</small>':''}</button>`).join('')}</div><div class="actions"><button class="button accent" data-action="job-next" ${state.jobId?'':'disabled'}>직무 선택 완료 →</button></div></main>`);}
function orgPage(){const links=state.companyType==='public'?[['국민건강보험공단','https://www.nhis.or.kr/nhis/index.do'],['한국보건산업진흥원','https://www.khidi.or.kr/'],['한국보건의료인국가시험원','https://www.kuksiwon.or.kr/']]:[['삼성 커리어스','https://www.samsungcareers.com/'],['Philips Healthcare Careers','https://www.careers.philips.com/'],['Medtronic Careers','https://jobs.medtronic.com/'],['Roche Careers','https://careers.roche.com/']];const linkCards=links.map(([label,url])=>`<a class="career-link" href="${url}" target="_blank" rel="noreferrer"><span>${label}</span><strong>↗</strong></a>`).join('');app.innerHTML=header(`<main><div class="eyebrow"> ORGANIZATION</div><h1>${state.companyType==='public'?'지원 기관':'지원 기업'}을 정해보세요</h1><p class="lead">${state.companyType==='public'?'기관의 주요 사업과 지원 직무의 역할을 먼저 조사하세요.':'공식 채용 홈페이지와 핵심가치·인재상을 직접 조사하세요.'}</p><div class="field"><label>지원${state.companyType==='public'?' 기관':' 기업'}</label><input id="org" value="${esc(state.organization)}" placeholder="지원할 곳을 입력하세요"></div><section class="career-links"><div><div class="mono">${state.companyType==='public'?'PUBLIC HEALTH REFERENCES':'HEALTHCARE TALENT REFERENCES'}</div><h3>${state.companyType==='public'?'기관의 사업과 직무 역할을 확인하세요.':'헬스케어 기업의 인재상과 채용 기준을 확인하세요.'}</h3></div><div class="career-link-grid">${linkCards}</div></section>${state.companyType==='public'?'<div class="blind"><strong>BLIND RECRUITMENT MODE</strong>직무와 직접 관계없는 개인정보를 작성하지 않습니다.</div>':''}<div class="actions"><button class="button accent" data-action="org-next">채용정보 확인 →</button></div></main>`);}
function essay(){const qs=state.questions||buildQuestions(state.companyType,state.jobId);state.questions=qs;const q=qs[state.questionIndex];app.innerHTML=header(`<main><div class="essay-heading"><div class="eyebrow">APPLICATION ESSAY · QUESTION 0${state.questionIndex+1}</div><button class="career-check-button" data-action="view-career">본인 경력 확인하기</button></div><div class="steps">${qs.map((_,i)=>`<div class="step ${i===state.questionIndex?'active':''}">0${i+1} ${i<state.questionIndex?'●':'○'}</div>`).join('')}</div><h2>${q.question}</h2><div class="guide">작성 구조: ${q.writingGuide}</div><textarea id="answer" maxlength="700" placeholder="나의 경험과 생각을 직접 작성해보세요.">${esc(state.answers[q.id]||'')}</textarea><div class="counter"><span id="count">${(state.answers[q.id]||'').length}</span> / 700</div><div class="actions"><button class="button secondary" data-action="previous" ${state.questionIndex===0?'disabled':''}>← 이전 문항</button><button class="button accent" data-action="next">${state.questionIndex===4?'완료':'다음 문항 →'}</button></div></main>`);document.querySelector('#answer').addEventListener('input',e=>{state.answers[q.id]=e.target.value;save();document.querySelector('#count').textContent=e.target.value.length;});}
function complete(){const labels=state.purchased.map(id=>experiences.find(x=>x[0]===id)?.[1]).filter(Boolean);app.innerHTML=header(`<main class="completion-page"><div class="completion-card"><div class="eyebrow">APPLICATION COMPLETE</div><h1>미래의 지원서가<br><span>완성되었습니다.</span></h1><p>작성한 경험과 답변이 Future Resume에 저장되었습니다.</p><div class="completion-summary"><span>지원 직무</span><strong>${state.jobId||'선택한 직무'}</strong><span>연결한 경험</span><strong>${labels.length}개 + SHIFT Bonus</strong></div><button class="button accent" data-action="future-resume">FUTURE RESUME 확인하기 →</button></div></main>`);}
function resume(){const labels=state.purchased.map(id=>experiences.find(x=>x[0]===id)?.[1]).filter(Boolean);app.innerHTML=header(`<main class="completion-page"><div class="eyebrow">FUTURE RESUME</div><h1>나의 미래<br><span>지원 기록</span></h1><div class="resume-panel"><div><span>APPLICATION STATUS</span><strong>COMPLETED</strong></div><div><span>SELECTED JOB</span><strong>${state.jobId||'선택한 직무'}</strong></div><div><span>CAREER EXPERIENCE</span><strong>${labels.length}개 + SHIFT Bonus</strong></div></div><div class="tags">${labels.map(label=>`<span class="tag">#${label}</span>`).join('')}</div><button class="button accent" data-action="submit-application">제출하기 →</button></main>`);}
function submitApplication(){const type=state.companyType==='public'?'PUBLIC':'PRIVATE';const typeLabel=state.companyType==='public'?'공기업·공공기관':'사기업';const labels=state.purchased.map(id=>experiences.find(x=>x[0]===id)?.[1]).filter(Boolean);const qs=state.questions||[];const subject=`[FUTURE CAREER / ${type}] ${state.name||'지원자'} / ${state.jobId||'직무'}`;const lines=[`채용 유형: ${typeLabel}`,`지원 기업/기관: ${state.organization||'미입력'}`,`선택 직군: ${state.jobId||'미입력'}`,`Blind Recruitment Mode: ${state.companyType==='public'?'YES':'NO'}`,`Career Experience: ${labels.join(', ')||'없음'}`,`SHIFT Bonus: ${state.gift||'없음'}`,'','APPLICATION ESSAY'];qs.forEach((q,index)=>{lines.push(`Q${index+1} [${q.competency}] ${q.question}`);lines.push(`답변: ${state.answers[q.id]||'미작성'}`);lines.push('');});const gmailUrl=`https://mail.google.com/mail/?view=cm&fs=1&to=shiftysdh@gmail.com&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join('\n'))}`;state.submitted=true;save();window.open(gmailUrl,'_blank');}
app.addEventListener('click',e=>{const reset=e.target.closest('[data-action="reset-demo"]');if(reset){localStorage.removeItem(KEY);state={...initial};clearTimeout(timer);timer=null;render();return;}const category=e.target.closest('[data-category]');if(category){state.category=category.dataset.category;save();render();return;}const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.buy)return;if(b.dataset.type)return go('job',{companyType:b.dataset.type,jobId:null,questions:null});if(b.dataset.job){state.jobId=b.dataset.job;save();render();return;}if(a==='home')return go(state.coinsAwarded?'shop':'splash');if(a==='finish-shop'){state.gift=gifts[Math.floor(Math.random()*gifts.length)];state.giftOpened=false;return go('mystery');}if(a==='open-gift'){state.giftOpened=true;save();render();return;}if(a==='confirm-gift')return go('type');if(a==='mystery')return go('mystery');if(a==='recruit')return go('recruit');if(a==='type')return go('type');if(a==='job-next')return go('org');if(a==='org-next'){state.organization=document.querySelector('#org').value.trim()||'미정 조직';return go('essay',{questionIndex:0,questions:buildQuestions(state.companyType,state.jobId)});}if(a==='previous'&&state.questionIndex>0)return go('essay',{questionIndex:state.questionIndex-1});if(a==='future-resume')return go('resume');if(a==='submit-application')return submitApplication();if(a==='next'){if(state.questionIndex<4)return go('essay',{questionIndex:state.questionIndex+1});return go('complete');}});
+render();
app.addEventListener('click',event=>{if(event.target.closest('[data-action="claim-coins"]')){const reward=Number(document.querySelector('.gacha-reward')?.textContent.replace(/\D/g,'')||0);state.coins=reward;state.coinsAwarded=true;go('shop');}});
app.addEventListener('click',event=>{if(event.target.closest('[data-action="view-career"]'))openCareerReview();if(event.target.closest('[data-action="close-career-review"]'))document.querySelector('.career-review-modal')?.remove();});
function openCareerReview(){const labels=state.purchased.map(id=>experiences.find(x=>x[0]===id)?.[1]).filter(Boolean);const counts=[...new Set(labels)].map(label=>`<li><span>${label}</span><strong>${labels.filter(item=>item===label).length}개</strong></li>`).join('');app.insertAdjacentHTML('beforeend',`<div class="modal-backdrop career-review-modal"><section class="modal career-review-panel" role="dialog" aria-modal="true"><div class="essay-heading"><div><div class="eyebrow">MY CAREER INVENTORY</div><h2>본인 경력 확인하기</h2></div><button class="career-close-button" data-action="close-career-review">닫기</button></div><p>Career Shop에서 구매한 경험과 SHIFT Bonus를 확인할 수 있습니다.</p><ul class="career-review-list">${counts||'<li><span>구매한 경험이 없습니다.</span></li>'}</ul>${state.gift?`<div class="career-bonus"><span>SHIFT BONUS</span><strong>${state.gift}</strong></div>`:''}</section></div>`);}
app.addEventListener('click',event=>{if(event.target.closest('[data-action="cancel-reward"]')){const result=document.querySelector('.gacha-result');if(result)result.style.display='none';}});
app.addEventListener('click',event=>{const buy=event.target.closest('[data-buy]');if(!buy)return;event.stopPropagation();event.preventDefault();const item=experiences.find(x=>x[0]===buy.dataset.buy);if(item)openPurchaseConfirm(item);},true);
app.addEventListener('click',event=>{const increase=event.target.closest('[data-increase]');if(increase){event.stopPropagation();const item=experiences.find(x=>x[0]===increase.dataset.increase);if(item&&state.coins>=item[4]){state.coins-=item[4];state.purchased.push(item[0]);save();render();showPurchaseNotice(`${item[1]} ${item[4]} COINS 추가 구매 완료했습니다.`);}else if(item){showPurchaseNotice(`COINS가 부족합니다. ${item[1]} 구매에는 ${item[4]} COINS가 필요합니다.`);}return;}const decrease=event.target.closest('[data-decrease]');if(decrease){event.stopPropagation();const item=experiences.find(x=>x[0]===decrease.dataset.decrease);if(item){const count=state.purchased.filter(id=>id===item[0]).length;if(count<=1)openCancelConfirm(item);else{state.purchased.splice(state.purchased.lastIndexOf(item[0]),1);state.coins+=item[4];save();render();showPurchaseNotice(`${item[1]} 1개를 줄였습니다. ${item[4]} COINS가 환불되었습니다.`);}}return;}},true);
function openPurchaseConfirm(item){app.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><section class="modal purchase-modal" role="dialog" aria-modal="true"><div class="eyebrow">PURCHASE CHECK</div><h2>${item[1]}을 구매할까요?</h2><div class="purchase-cost">◈ ${item[4]} COINS</div><p>구매 후 MY CAREER에서 이 경험을 자기소개서 문항에 연결할 수 있습니다.</p><div class="actions"><button class="button secondary" data-action="cancel-purchase">취소</button><button class="button accent" data-action="confirm-purchase" data-purchase="${item[0]}">구매 확인</button></div></section></div>`);}
function openCancelConfirm(item){app.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><section class="modal purchase-modal" role="dialog" aria-modal="true"><div class="eyebrow">CANCEL PURCHASE</div><h2>${item[1]} 1개를 취소할까요?</h2><div class="purchase-cost">${item[4]} COINS 환불</div><p>보유 경험 1개가 inventory에서 제거되고 코인이 환불됩니다.</p><div class="actions"><button class="button secondary" data-action="dismiss-cancel">돌아가기</button><button class="button accent" data-action="confirm-cancel" data-cancel-confirm="${item[0]}">구매 취소</button></div></section></div>`);}
app.addEventListener('click',event=>{const action=event.target.closest('button')?.dataset.action;if(action==='confirm-purchase'){const item=experiences.find(x=>x[0]===event.target.closest('button').dataset.purchase);document.querySelector('.modal-backdrop')?.remove();if(item){state.coins-=item[4];state.purchased.push(item[0]);save();render();showPurchaseNotice(`${item[1]} ${item[4]} 코인 구매 완료했습니다!`);}}if(action==='cancel-purchase'){document.querySelector('.modal-backdrop')?.remove();showPurchaseNotice('구매를 취소했습니다.');}if(action==='confirm-cancel'){const item=experiences.find(x=>x[0]===event.target.closest('button').dataset.cancelConfirm);document.querySelector('.modal-backdrop')?.remove();if(item){const index=state.purchased.lastIndexOf(item[0]);if(index>-1){state.purchased.splice(index,1);state.coins+=item[4];save();render();showPurchaseNotice(`${item[1]} 1개 구매를 취소했습니다. ${item[4]} COINS가 환불되었습니다.`);}}}if(action==='dismiss-cancel'||action==='close-purchase-notice')document.querySelector('.modal-backdrop')?.remove();});
app.addEventListener('click',event=>{const button=event.target.closest('button');const action=button?.dataset.action;if(action==='confirm-cancel'){const item=experiences.find(x=>x[0]===button.dataset.cancelConfirm);document.querySelector('.modal-backdrop')?.remove();if(item){const index=state.purchased.lastIndexOf(item[0]);if(index>-1){state.purchased.splice(index,1);state.coins+=item[4];save();render();showPurchaseNotice(`${item[1]} 1개 구매를 취소했습니다. ${item[4]} COINS가 환불되었습니다.`);}}}if(action==='dismiss-cancel')document.querySelector('.modal-backdrop')?.remove();});
function showPurchaseNotice(message){app.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><section class="modal purchase-modal" role="alert"><div class="eyebrow">CAREER SHOP</div><h2>${message}</h2><button class="button accent" data-action="close-purchase-notice">확인</button></section></div>`);}
