import { JOBS, CAREER_EXPERIENCES, buildQuestions } from './question-bank.js';

const KEY = 'future-career-application-v1';
const initial = { screen:'splash', companyType:null, jobId:null, organization:'', name:'', answers:{}, experiences:{}, questionIndex:0, questions:null, blindSeen:false, submitted:false, coins:0, coinsAwarded:false, purchasedExperiences:[] };
let state = { ...initial, ...JSON.parse(localStorage.getItem(KEY) || '{}') };
if (!state.coinsAwarded) state.screen = 'splash';
let splashTimer;
const app = document.querySelector('#app');
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const setState = (patch) => { state = { ...state, ...patch }; save(); render(); };
const esc = (value='') => value.replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const job = () => JOBS.find((item) => item.id === state.jobId);
const questions = () => state.questions || (state.companyType && state.jobId ? buildQuestions(state.companyType, state.jobId) : []);
const typeName = () => state.companyType === 'public' ? '공기업·공공기관' : '사기업';
const shopItems = [
  { id:'intern', label:'기업 인턴', detail:'조직의 실제 문제를 가까이서 관찰한 경험', cost:18 },
  { id:'research', label:'학부연구생', detail:'질문을 세우고 검증하는 탐구 경험', cost:15 },
  { id:'contest', label:'공모전 우수상', detail:'제한된 시간 안에 결과를 만든 도전', cost:20 },
  { id:'council', label:'학생회 국장', detail:'사람과 목표를 연결한 협업 경험', cost:12 },
  { id:'healthcare-data', label:'헬스케어 데이터 프로젝트', detail:'데이터로 문제를 정의하고 해석한 경험', cost:22 },
  { id:'shift-planning', label:'SHIFT 프로그램 기획 경험', detail:'사용자 관점에서 프로그램을 설계한 경험', cost:16 }
];
const shell = (content) => `<div class="app-shell ${state.companyType === 'public' ? 'public-mode' : ''}"><header class="topbar"><button class="home-button" data-action="home" aria-label="홈으로 이동"><span aria-hidden="true">⌂</span><span>HOME</span></button><div class="logo">FUTURE <span>CAREER</span></div><div class="mono">APPLICATION STUDIO / 2026</div></header><div class="progress"><i style="width:${state.screen === 'mystery' ? 12 : state.screen === 'review' ? 100 : 30 + Math.min(state.questionIndex, 5) * 12}%"></i></div>${content}<div id="toast" class="toast"></div></div>`;
const layout = (title, eyebrow, body, actions='') => `<main><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${body}${actions}</main>`;
function render() {
  if (state.screen === 'splash') return renderSplash();
  if (state.screen === 'gacha') return renderGacha();
  if (state.screen === 'shop') return renderShop();
  if (state.screen === 'mystery') return renderMystery();
  if (state.screen === 'type') return renderType();
  if (state.screen === 'job') return renderJob();
  if (state.screen === 'organization') return renderOrganization();
  if (state.screen === 'info') return renderInfo();
  if (state.screen === 'essay') return renderEssay();
  if (state.screen === 'review') return renderReview();
}
function renderSplash() { app.innerHTML = `<div class="splash-screen"><div class="splash-mark"><div class="splash-kicker">MY FUTURE, MY SHIFT</div><div class="splash-logo">FUTURE <span>RESUME</span></div><p>나의 경험을 미래의 지원서로</p></div></div>`; if (!splashTimer) splashTimer = setTimeout(() => { state.screen='gacha'; splashTimer=null; render(); },1500); }
function renderGacha() { const reward=Math.floor(Math.random()*31)+40; app.innerHTML=`<div class="gacha-screen"><div class="gacha-copy"><div class="splash-kicker">SHIFT LUCKY DROP</div><h1>오늘의 미래 코인을<br><span>뽑아보세요.</span></h1><p>가챠 머신이 당신의 첫 Career Shop 코인을 준비하고 있습니다.</p></div><div class="gacha-machine" aria-label="코인 가챠 랜덤 머신"><div class="machine-top"><span></span><span></span><span></span><span></span><span></span></div><div class="machine-glass"><div class="capsule capsule-one"></div><div class="capsule capsule-two"></div><div class="capsule capsule-three"></div><div class="capsule capsule-four"></div><div class="capsule capsule-five"></div><div class="winning-capsule">◈</div></div><div class="machine-base"><div class="machine-label">FUTURE<br>RESUME</div><div class="machine-slot"></div><div class="machine-knob"></div></div></div><div class="gacha-status"><span class="status-shuffle">CAPSULES SHUFFLING · · ·</span><span class="status-reveal">YOUR CAPSULE IS READY</span><strong class="gacha-reward">◈ ${reward}</strong></div></div>`; if (!splashTimer) splashTimer=setTimeout(()=>{state.coins=reward;state.coinsAwarded=true;state.screen='shop';splashTimer=null;save();render();},4300); }
function renderShop() { const owned=state.purchasedExperiences||[]; const cards=shopItems.map(item=>`<article class="shop-item ${owned.includes(item.id)?'owned':''}"><div class="shop-icon">✦</div><div><div class="mono">CAREER EXPERIENCE</div><h3>${item.label}</h3><p>${item.detail}</p></div><div class="shop-item-footer"><span class="coin-cost">◈ ${item.cost}</span>${owned.includes(item.id)?'<span class="owned-label">보유 중</span>':`<button class="button small" data-buy="${item.id}" ${state.coins<item.cost?'disabled':''}>구매하기</button>`}</div></article>`).join(''); app.innerHTML=shell(layout('나의 미래 경험을 골라보세요','01 / CAREER SHOP',`<div class="shop-header"><p class="lead">지금 가진 코인으로 미래의 나에게 필요한 경험을 선택하세요. 구매한 경험은 이후 자기소개서 문항에 연결할 수 있습니다.</p><div class="coin-wallet"><span class="wallet-label">MY COINS</span><strong>◈ ${state.coins}</strong></div></div><div class="shop-grid">${cards}</div><div class="shop-note"><span class="badge">NO AI WRITING</span><span>경험을 고르는 일은 답변을 대신 작성하는 일이 아닙니다.</span></div>`,`<div class="actions"><button class="button accent" data-action="to-mystery">선택 완료 · MYSTERY BOX 열기 →</button></div>`)); }
function renderMystery() { const owned=(state.purchasedExperiences||[]).map(id=>shopItems.find(item=>item.id===id)?.label).filter(Boolean); app.innerHTML=shell(layout('SHIFT Mystery Box','02 / UNLOCK YOUR NEXT MOVE',`<p class="lead">Career Shop에서 모은 경험이 다음 선택의 단서가 됩니다.</p><div class="panel" style="margin-top:30px"><span class="badge">CAREER SHOP COMPLETE</span><h3>당신의 다음 장면을 준비했습니다.</h3><p>보유 경험 ${owned.length}개 · SHIFT Bonus 1개</p><div class="tags">${owned.length?owned.map(item=>`<span class="tag">#${item}</span>`).join(''):'<span class="mono">아직 선택한 경험이 없습니다.</span>'}</div></div>`,`<div class="actions"><button class="button accent" data-action="open-box">MYSTERY BOX 열기 →</button></div>`)); }
function renderType() { app.innerHTML=shell(layout('어떤 조직의 미래에 지원하시겠습니까?','03 / WHERE DO YOU WANT TO WORK?','<p class="lead">선택 결과는 지원서와 자기소개서 문항을 구성하는 데 사용됩니다.</p><div class="cards"><article class="card"><div class="icon">🏢</div><h3>PRIVATE COMPANY</h3><p>성과와 성장, 직무 전문성, 기업의 핵심가치를 중심으로 작성합니다.</p><button class="button" data-type="private">사기업 지원하기 →</button></article><article class="card"><div class="icon">🏛</div><h3>PUBLIC INSTITUTION</h3><p>직무수행능력, 문제해결, 직업윤리와 공공성을 중심으로 작성합니다.</p><button class="button" data-type="public">공기업·공공기관 지원하기 →</button></article></div>')); }
function renderJob() { const list=state.companyType==='public'?JOBS:[...JOBS].sort((a,b)=>Number(a.public)-Number(b.public)); const body=`<p class="lead">${state.companyType==='public'?'공공기관 활용도가 높은 직군을 먼저 배치했습니다.':'관심 있는 직군을 선택하면 맞춤 문항이 연결됩니다.'}</p><div class="job-grid">${list.map(item=>`<button class="job ${item.id===state.jobId?'selected':''}" data-job="${item.id}"><strong>${item.label}</strong>${item.public?'<small>Public-ready</small>':''}</button>`).join('')}</div>`; app.innerHTML=shell(layout('지원 직무를 선택하세요',`${typeName()} / 04 JOB CATEGORY`,body,`<div class="actions"><button class="button secondary" data-action="back-type">← 이전</button><button class="button accent" data-action="next-job" ${state.jobId?'':'disabled'}>직무 선택 완료 →</button></div>`)); }
function renderOrganization() { app.innerHTML=shell(layout('지원할 곳을 정해보세요',`${typeName()} / 05 ORGANIZATION`,`<div class="panel-grid"><section><h2>${state.companyType==='public'?'기관의 주요 사업을 먼저 조사하세요.':'기업의 공식 채용 페이지를 조사하세요.'}</h2><p>${state.companyType==='public'?'기관의 주요 사업과 지원 직무의 역할을 먼저 살펴보세요.':'공식 채용 홈페이지와 핵심가치·인재상을 직접 조사해보세요.'}</p><div class="field"><label>${state.companyType==='public'?'지원 기관':'지원 기업'}</label><input id="organization" value="${esc(state.organization)}" placeholder="지원할 곳을 입력하세요"></div></section><aside class="panel"><span class="badge">SELECTED JOB</span><h3>${job()?.label}</h3></aside></div>${state.companyType==='public'?'<div class="blind"><strong>BLIND RECRUITMENT MODE</strong>직무 관련 경험과 역량 중심으로 작성합니다.</div>':''}`,`<div class="actions"><button class="button secondary" data-action="back-job">← 이전</button><button class="button accent" data-action="next-org">채용정보 확인 →</button></div>`)); }
function renderInfo() { app.innerHTML=shell(layout('지원서를 시작하기 전, 방향을 확인하세요',`${typeName()} / 06 APPLICATION BRIEF`,`<div class="panel"><span class="badge">${state.companyType==='public'?'PUBLIC FOCUS':'PRIVATE FOCUS'}</span><h2>${state.companyType==='public'?'기관의 문제를 이해하고 공공의 가치를 설명하세요.':'기업의 방향과 나의 성장을 연결하세요.'}</h2><p>${state.companyType==='public'?'직무수행능력, 의사소통, 문제해결, 조직이해, 직업윤리, 공공성을 중심으로 답변합니다.':'기업 핵심가치, 직무 전문성, 지원동기, 성과, 도전, 협업, 성장 가능성을 중심으로 답변합니다.'}</p></div>${state.companyType==='public'?'<div class="blind"><strong>BLIND RECRUITMENT 안내</strong>직무와 직접 관계없는 개인정보를 작성하지 마세요. 교육 목적의 시뮬레이션입니다.</div>':''}`,`<div class="actions"><button class="button secondary" data-action="back-org">← 이전</button><button class="button accent" data-action="start-essay">지원서 작성 시작 →</button></div>`)); }
function renderEssay() { const list=questions(); const q=list[state.questionIndex]; const answer=state.answers[q.id]||''; const selected=state.experiences[q.id]||[]; const isRandom=q.random; app.innerHTML=shell(`<main><div class="eyebrow">APPLICATION ESSAY <span class="badge">${typeName()}</span></div><div class="steps">${list.map((item,i)=>`<div class="step ${i===state.questionIndex?'active':''}">0${i+1} ${i<state.questionIndex?'●':'○'}</div>`).join('')}</div>${isRandom&&!state.revealed?`<div class="reveal"><div class="eyebrow">SPECIAL QUESTION</div><h2>지원자의 또 다른 모습을 알고 싶습니다.</h2><button class="button accent" data-action="reveal">질문 확인하기</button></div>`:`<div class="question-meta"><div><div class="eyebrow">QUESTION 0${state.questionIndex+1} · ${q.competency.toUpperCase()}</div><h2>${q.question}</h2></div><div class="counter"><span id="count">${answer.length}</span> / 700</div></div><div class="guide">작성 구조: ${q.writingGuide}</div><div class="field"><label>이 문항에 활용할 경험</label><div class="tags">${selected.map(id=>`<span class="tag">#${id}</span>`).join('')}</div><button class="button secondary" data-action="career">MY CAREER 불러오기</button></div><textarea id="answer" maxlength="700" placeholder="나의 경험과 생각을 직접 작성해보세요.">${esc(answer)}</textarea><div class="actions"><button class="button secondary" data-action="prev">← 이전 문항</button><button class="button secondary" data-action="save-answer">임시저장</button><button class="button accent" data-action="next">${state.questionIndex===4?'최종 확인 →':'다음 문항 →'}</button></div>`}</main>`); if(!isRandom||state.revealed) document.querySelector('#answer')?.addEventListener('input',event=>{state.answers[q.id]=event.target.value;save();document.querySelector('#count').textContent=event.target.value.length;}); }
function renderReview() { const list=questions(); app.innerHTML=shell(layout('최종 제출 전, 미래의 지원서를 확인하세요',state.companyType==='public'?'BLIND RECRUITMENT APPLICATION':'APPLICATION REVIEW',`<div class="panel"><div class="mono">APPLICATION INFORMATION</div><h3>${esc(state.name||'이름 미입력')}</h3><p>채용유형: ${typeName()}<br>지원${state.companyType==='public'?'기관':'기업'}: ${esc(state.organization)}<br>지원직무: ${job()?.label}</p></div><div class="review"><div class="mono">APPLICATION ESSAY</div>${list.map((q,i)=>`<article class="review-item"><div class="eyebrow">Q${i+1} · ${q.competency}</div><h3>${q.question}</h3><p>${esc(state.answers[q.id]||'작성된 답변이 없습니다.')}</p></article>`).join('')}</div><div class="field"><label>제출자 이름</label><input id="name" value="${esc(state.name)}" placeholder="이름을 입력하세요"></div>`,`<div class="actions"><button class="button secondary" data-action="back-essay">← 수정하기</button><button class="button accent" data-action="submit">Gmail로 최종 제출 →</button></div>`)); }
app.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;const action=target.dataset.action;if(target.dataset.buy){const item=shopItems.find(shopItem=>shopItem.id===target.dataset.buy);if(!item||state.coins<item.cost)return;state.coins-=item.cost;state.purchasedExperiences=[...(state.purchasedExperiences||[]),item.id];save();render();return;}if(target.dataset.type){setState({companyType:target.dataset.type,screen:'job',jobId:null,questions:null,questionIndex:0,revealed:false});return;}if(target.dataset.job){state.jobId=target.dataset.job;save();render();return;}if(action==='home'){setState({screen:state.coinsAwarded?'shop':'splash'});return;}if(action==='to-mystery')setState({screen:'mystery'});if(action==='open-box')setState({screen:'type'});if(action==='back-type')setState({screen:'type'});if(action==='next-job')setState({screen:'organization'});if(action==='back-job')setState({screen:'job'});if(action==='next-org'){state.organization=document.querySelector('#organization').value.trim()||'미정 조직';setState({screen:'info'});}if(action==='back-org')setState({screen:'organization'});if(action==='start-essay'){if(state.companyType==='public'&&!state.blindSeen)openBlindModal();else beginEssay();}if(action==='confirm-blind'){document.querySelector('.modal-backdrop')?.remove();state.blindSeen=true;save();beginEssay();}if(action==='reveal'){state.revealed=true;save();render();}if(action==='career')openCareer();if(action==='save-answer'){save();showToast('현재 문항을 임시저장했습니다.');}if(action==='prev'&&state.questionIndex>0){state.questionIndex--;state.revealed=false;save();render();}if(action==='next'){if(state.questionIndex<4){state.questionIndex++;state.revealed=false;save();render();}else setState({screen:'review'});}if(action==='back-essay')setState({screen:'essay',questionIndex:4,revealed:false});if(action==='submit')submit();});
+function beginEssay(){if(!state.questions)state.questions=buildQuestions(state.companyType,state.jobId);setState({screen:'essay',questionIndex:0,revealed:false});}
+function openBlindModal(){app.insertAdjacentHTML('beforeend','<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><div class="eyebrow">BLIND RECRUITMENT</div><h2>블라인드 채용 안내</h2><p>직무와 직접 관계없는 개인정보를 작성하지 마세요. 본 프로그램은 교육 목적의 시뮬레이션입니다.</p><button class="button accent" data-action="confirm-blind">안내를 확인했습니다 →</button></section></div>');}
+function openCareer(){const q=questions()[state.questionIndex];const chosen=state.experiences[q.id]||[];document.body.insertAdjacentHTML('beforeend',`<div class="panel" style="position:fixed;right:0;top:0;bottom:0;width:min(410px,100%);z-index:3"><div style="display:flex;justify-content:space-between"><h3>MY CAREER</h3><button class="button secondary" data-action="close-career">닫기</button></div><p>활용할 경험을 선택하세요.</p><div class="side-list">${CAREER_EXPERIENCES.map(item=>`<label class="experience"><span>${item}</span><input type="checkbox" data-exp="${item}" ${chosen.includes(item)?'checked':''}></label>`).join('')}</div><button class="button accent" data-action="apply-career">선택 경험 연결</button></div>`);}
+function submit(){state.name=document.querySelector('#name').value.trim()||'이름 미입력';save();const subject=`[FUTURE CAREER / ${state.companyType==='public'?'PUBLIC':'PRIVATE'}] / ${state.name} / ${job()?.label}`;const body=[`채용 유형: ${typeName()}`,`선택 직군: ${job()?.label}`,...questions().flatMap((q,i)=>[`Q${i+1} [${q.competency}] ${q.question}`,state.answers[q.id]||'미작성',''])].join('\n');window.location.href=`mailto:shiftysdh@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}
+app.addEventListener('change',event=>{if(event.target.dataset.exp){const q=questions()[state.questionIndex];const selected=new Set(state.experiences[q.id]||[]);event.target.checked?selected.add(event.target.dataset.exp):selected.delete(event.target.dataset.exp);state.experiences[q.id]=[...selected];save();}});
+app.addEventListener('click',event=>{if(event.target.dataset.action==='close-career')event.target.closest('.panel').remove();if(event.target.dataset.action==='apply-career'){event.target.closest('.panel').remove();render();}});
+function showToast(message){const toast=document.querySelector('#toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);}
+render();
